name: Run Docker Compose

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        
      - name: Build and Run Docker Compose
        run: |
          docker-compose up -d
          sleep 5

      - name: Execute start.sh script
        run: |
          docker exec -i postgres-container sh -c "chmod +x ./setup.sh && ./setup.sh"

      - name: Install dependencies
        run: npm i
  
      - name: Run Cypress tests
        run: npx cypress run --spec ./cypress/e2e/

      - name: Select all users
        run: |
          docker exec -i postgres-container psql -h localhost -U testuser -d test_name -c "SELECT * FROM users;"

