name: Run Docker Compose

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Run Docker Compose
        run: |
          docker-compose up -d
          sleep 5

      - name: Execute start.sh script
        run: |
          docker exec -i postgres-container sh -c "chmod +x ./setup.sh && ./setup.sh"
